# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)

##Specifing Jobs
jobs:
 ##Tasks performed to job1
- job: Job1
  steps:
  - script: echo Job1 - Hello, world, changed!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo more information
    displayName: 'Run a multi-line script'
  ##Tasks performed to job2
- job: Job2
  ##Jobs needed to run first
  dependsOn: Job1
  steps:
  - script: echo Job2!
    displayName: 'Run a one-line script'
  ###Tasks performed to job3
- job: Job3
  ##Jobs needed to run first
  dependsOn: Job1
  steps:
  - script: echo Job3!
    displayName: 'Run a one-line script'
  ##Tasks performed to job4
- job: Job4
  ##Jobs needed to run first
  dependsOn: 
  - Job2
  - Job3
  steps:
  - script: echo Job4!
    displayName: 'Run a one-line script'