trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


  steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

# init -backend
    - task: TerraformTaskV1@0
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
        backendServiceAWS: 'aws-for-terraform'
        backendAWSBucketName: 'terraform-backend-state-badalo'
        backendAWSKey: 'kubernetes-dev.tfstate'
#apply
    - task: TerraformTaskV1@0
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
        environmentServiceNameAWS: 'aws-for-terraform'
#Destroy(Not necessary)
    # - task: TerraformTaskV1@0
    #   inputs:
    #     provider: 'aws'
    #     command: 'destroy'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    #     environmentServiceNameAWS: 'aws-for-terraform'