trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

# Build
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          # Build Docker
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              Dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: "$(tag)"
          # Copy Files to Staging Directory(yaml files)
          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: "**/*.yaml"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          # Publish
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "manifests"
              publishLocation: "Container"

          # Deploy
          - stage: Deploy
            displayName: Deploy image
            jobs:
              - job: Deploy
                displayName: Deploy
                pool:
                  vmImage: "ubuntu-latest"
                steps:
                  # Download Artifacts
                  - task: DownloadPipelineArtifact@2
                    inputs:
                      buildType: "current"
                      artifactName: "manifests"
                      itemPattern: "**/*.yaml"
                      targetPath: "$(System.ArtifactsDirectory)"
                    # apply - kubectl apply -f deployment.yaml
                  - task: KubernetesManifest@0
                    inputs:
                      action: "deploy"
                      kubernetesServiceConnection: "aws-kubernetes-cluster-service-connection"
                      namespace: "default"
                      manifests: "$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml"
                      containers: badalo/currency-exchange-devops:$(tag)
