trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

#Stage1
#Build docker Image
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "badalo-docker-hub"
              repository: "badalo/currency-exchange-devops"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)"
          #Publish K8S Files
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/*.yaml'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "manifests"
              publishLocation: "Container"
  #Stage 2
  #Download the K8S Files
  - stage: Deploy
    displayName: Deploy image
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: "current"
              artifactName: "manifests"
              itemPattern: "**/*.yaml"
              targetPath: "$(System.ArtifactsDirectory)"
          #Deploy to K8S Cluster with Docker Image
          - task: KubernetesManifest@0
            inputs:
              action: "deploy"
              kubernetesServiceConnection: "azure-kubernetes-connection"
              namespace: "default"
              manifests: "$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml"
              containers: "badalo/currency-exchange-devops:$(tag)"
